backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "content"
    label: "İçerik"
    files:
      - name: "quote"
        label: "Günün Sözü"
        file: "content/quote.json"
        format: "json"
        fields:
          - { label: "Söz", name: "text", widget: "string" }
          - { label: "Kaynak", name: "source", widget: "string" }
