backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "Site Ayarları"
    files:
      - file: "settings/gunun-sozu.json"
        label: "Günün Sözü"
        name: "dailyQuote"
        fields:
          - { label: "Söz", name: "text", widget: "string" }
          - { label: "Kaynak (Ayet/Hadis)", name: "source", widget: "string" }
